channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0.1
- pip:
  - mlflow==3.8.0
  - cloudpickle==3.1.2
  - numpy==2.2.4
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.13.1
name: mlflow-env
